### ISSUE TITLE
400 message when retrieving conversation using guest token

### ISSUE THREAD

**Issue by levensailor** [webex/react-widgets#989]
Getting a 400 message in the chrome console
looks like widget-space cannot access the url below:

https://conv.a7.ciscospark.com/conversation/api/v1/activities?personRefresh=true&uuidEntryFormat=true&activitiesLimit=0&participantsLimit=0&lastActivityFirst=false&fetchConversationId=4e4204f2-a851-362f-b7b7-ab19cf2a64db&limit=50&fetchSinceDate=

traceback:
```js 
Uncaught (in promise) n: conversationId is null
undefined https://conv.a7.ciscospark.com/conversation/api/v1/activities
WEBEX_TRACKING_ID: webex-js-sdk_79a96c82-f97c-409d-aa6a-75ef0b1532ba_13

    at n (https://code.s4d.io/widget-space/production/bundle.js:415:595)
    at n (https://code.s4d.io/widget-space/production/bundle.js:415:197)
    at n (https://code.s4d.io/widget-space/production/bundle.js:226:974)
    at n (https://code.s4d.io/widget-space/production/bundle.js:99:520)
    at new n (https://code.s4d.io/widget-space/production/bundle.js:441:296)
    at n.value (https://code.s4d.io/widget-space/production/bundle.js:444:486)
    at https://code.s4d.io/widget-space/production/bundle.js:444:8720
```

**Comment by levensailor** [comment]
resolved in `latest`
